language: node_js
sudo: false
jobs:
  include:
  - language: node_js
  - stage: publish
    install:
    - npm install
    - pip install sphinx sphinx_rtd_theme --user
    script:
    - "make html -C doc SPHINXBUILD=~/.local/bin/sphinx-build WEBPACK=$(npm bin)/webpack BABEL=$(npm bin)/babel"
    - "touch doc/_build/html/.nojekyll"
    env:
      secure: "XVgwRUI/uHPXNlJ3yWqdGYATaHNU0MKTjiEd6gyAP5nTWooTZ8ew1bjtX5POGrtsL/RVN9am32gu2TBh9msCY+2Ksv7lim50j8dA66WLxTRyOE7/dIBDVgv/vF+ewzrltuG4GMwpW7jGAarjTwotBu5FxcBQINcX234NclniXJs7BsMnt/tYQ89GiP7tkDfsjg9OcO2b1ZMzcGMrssj9ga00MZds6X03pLfDbHuWCdi3DEqBY6h6Z55z4bdzhmJIOf/b+0CXknAcBFS+FqGNc5chdUmgN4okp7aurCeFDGE4tgRGScDg2YFcNTsUK683VKeYgqBsd8Fyv3otMuryfssw1GWnIcYNwHSIojqgfOPWWCdVQg4vw6YxWFyBwMaJy9ZF9tVR57+aXJPy51QtCHqgQDftXOhw42trhwJVt3P+kLrmvlmTc5XnRv/ks3BkDRoW4yvAOVINFFZ0WMYi7ABn6WxgmwomE95AZhND3/KOjLXBF7qG6GTPhHZZIdFz1mTrCr286u+uNTHpJrL+WwQQCd2LvN3eg+1WKBc2n8DYq6SQc0Z9vQP3vDrUzq43Plk1KguRcYciuy1UFWRsmi0Dz+ajvz1Sj3H5JXzrHhHbHR6tJGHL6eQboItcXTiYdafxpP+iqUumY5wlLJdAWQEifu2bFTzP0JfgEBjJ5dc="
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: "$GH_TOKEN"
      local_dir: doc/_build/html
      on:
        branch: master
  - stage: publish
    script: true
    before_deploy: |
      cd khufu-runtime
      npm run build
    deploy:
      provider: npm
      skip_cleanup: true
      email: "paul@colomiets.name"
      api_key:
        secure: "TjHJ96ZqGz5EgHNdx6WW/nc3fUzC7k4p9DcflfyOtwrBYa0sHZs6kF7lAdJZ8XoOToaTySIPMyzfvjMMIn6p9Z/9gKnSgjBNVSwbbhuEejHEjSfyLPcWuwX5OiMoiHNmRGMLEfrgL0VMPkK8qRuWzcyCaS38j1Z2sWISoJQnhe1Bo6P9I7HakGdPTIwKK2l820wAiuGASSh6GhzPrj1ysWT64wLCRCt/H5eBdk/krbxOoGSuqnrtv8KMDsWT/i/LNokjgOWMizACqqY+oxzs+qKntnYHYRXqzDltfbW94bm516cpdQHBhjRo5XXpIYYTWq/JSiKT9kkDqseW1lKOuEYJDJL/+kUkBQkzI7uLYhJxCuZJJ3L//CTdUo/EDOaJTrZxvPZSOHnzWdVV2NsjmCNLGnY5GRnut5oFBHamfwgSIM983s7j6S6slg9cP9bRlEW9DqRb3ZzuW7D76cXv9B9srFNVn7zC6/gU+yLBJr3unD5cEzDlaAEebYeBwDPYH/zVEoL54Ayd7+B+4Slyyk4U5WJy3k5QavhzT9jVfK8NEHP4YbLcXz6rm/iOl6swFdK9h2AX5CQJ5Knb3zEukmjR2fKL2M3F1/g9UPZ/aM8dtr4FX6T3Hw3M+JGjNbdPhNx3Y27LJ81+Ky+N95mZKmdOVVy9yk8l6h0PSeN/pBM="
      on:
        tags: true
  - stage: publish
    script: true
    deploy:
      provider: npm
      skip_cleanup: true
      email: "paul@colomiets.name"
      api_key:
        secure: "TjHJ96ZqGz5EgHNdx6WW/nc3fUzC7k4p9DcflfyOtwrBYa0sHZs6kF7lAdJZ8XoOToaTySIPMyzfvjMMIn6p9Z/9gKnSgjBNVSwbbhuEejHEjSfyLPcWuwX5OiMoiHNmRGMLEfrgL0VMPkK8qRuWzcyCaS38j1Z2sWISoJQnhe1Bo6P9I7HakGdPTIwKK2l820wAiuGASSh6GhzPrj1ysWT64wLCRCt/H5eBdk/krbxOoGSuqnrtv8KMDsWT/i/LNokjgOWMizACqqY+oxzs+qKntnYHYRXqzDltfbW94bm516cpdQHBhjRo5XXpIYYTWq/JSiKT9kkDqseW1lKOuEYJDJL/+kUkBQkzI7uLYhJxCuZJJ3L//CTdUo/EDOaJTrZxvPZSOHnzWdVV2NsjmCNLGnY5GRnut5oFBHamfwgSIM983s7j6S6slg9cP9bRlEW9DqRb3ZzuW7D76cXv9B9srFNVn7zC6/gU+yLBJr3unD5cEzDlaAEebYeBwDPYH/zVEoL54Ayd7+B+4Slyyk4U5WJy3k5QavhzT9jVfK8NEHP4YbLcXz6rm/iOl6swFdK9h2AX5CQJ5Knb3zEukmjR2fKL2M3F1/g9UPZ/aM8dtr4FX6T3Hw3M+JGjNbdPhNx3Y27LJ81+Ky+N95mZKmdOVVy9yk8l6h0PSeN/pBM="
      on:
        tags: true
